// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protos/user.proto

package message

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	GetUserById(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*UserIdReply, error)
	Test(ctx context.Context, in *ApplicationRequest, opts ...client.CallOption) (*ApplicationDetailReply, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUserById(ctx context.Context, in *UserIdRequest, opts ...client.CallOption) (*UserIdReply, error) {
	req := c.c.NewRequest(c.name, "User.GetUserById", in)
	out := new(UserIdReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Test(ctx context.Context, in *ApplicationRequest, opts ...client.CallOption) (*ApplicationDetailReply, error) {
	req := c.c.NewRequest(c.name, "User.Test", in)
	out := new(ApplicationDetailReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	GetUserById(context.Context, *UserIdRequest, *UserIdReply) error
	Test(context.Context, *ApplicationRequest, *ApplicationDetailReply) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		GetUserById(ctx context.Context, in *UserIdRequest, out *UserIdReply) error
		Test(ctx context.Context, in *ApplicationRequest, out *ApplicationDetailReply) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) GetUserById(ctx context.Context, in *UserIdRequest, out *UserIdReply) error {
	return h.UserHandler.GetUserById(ctx, in, out)
}

func (h *userHandler) Test(ctx context.Context, in *ApplicationRequest, out *ApplicationDetailReply) error {
	return h.UserHandler.Test(ctx, in, out)
}
